### PR TITLE
new-window link for http://localhost:3000

### PR DESCRIPTION
**Pull request by tflinz**
ease-of-use for http://localhost:3000, so it launches in new tab/window

### CODE REVIEW

**Comment by tflinz** [comment]
oh, I was just following this when I made the edit:
https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link

**Comment by tflinz** [comment]
but even that fix seems iffy for support. so might not be possible :s

**Comment by tflinz** [comment]
apparently this might be a better approach? https://stackoverflow.com/a/29767900/1161429

**Comment by brandon-swu** [comment]
Those are all good and definitely make sense to do the job, but what I was getting at is a simple link would suffice. Users can pick whether they want to open in a new tab by right-clicking, or CMD/Ctrl+click'ing the link.

**Pull request closed without merging**
